### ISSUE TITLE
Overlay does not close the game when using the Exit button 

### ISSUE THREAD

**Issue by nyghtstalker** [HyperPlay-Gaming/hyperplay-desktop-client#492]
### Describe the bug

When a user attempts to close the game via the overlay Exit button with The Fabled launched the overlay does close, however, the game remains open. We have to force close the game in order for it to close.

**CONFIRMED:** 

**- Exit button does _DOES_ work on Mac -  _Windows only_**

**- Mint - The game does not seem to launch on Mint but the overlay does and the Exit button does NOT close the overlay**

### Add logs

```
(09:47:42) INFO:    [Legendary]:        Refreshing library...
(09:47:42) INFO:    [Legendary]:        Refreshing Epic Games...
(09:47:42) INFO:    [Backend]:          Loading MetaMask extension
(09:47:42) INFO:    [Connection]:       Connectivity: check-online
(09:47:42) INFO:    [Connection]:       Pinging external endpoints
(09:47:42) INFO:    [Backend]:          Creating abort controller for legendary-version
(09:47:42) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(09:47:42) INFO:    [Legendary]:        Legendary location: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary
(09:47:42) INFO:    [Gog]:              GOGDL location: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl
(09:47:42) INFO:    [Gog]:              GOGDL location: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl
(09:47:42) INFO:    [Legendary]:        Game list updated, got 356 games & DLCs
(09:47:42) WARNING: [Backend]:          Protocol already registered.
(09:47:42) INFO:    [Backend]:          App is starting in headless mode = undefined isCLINoGui = false startInTray = undefined
(09:47:42) INFO:    [Backend]:          MetaMask extension loaded
(09:47:43) INFO:    [Backend]:          Creating abort controller for legendary-refresh
(09:47:43) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(09:47:43) INFO:    [Connection]:       Connectivity: online
(09:47:43) INFO:    [Gog]:              Getting data about the user
(09:47:43) WARNING: [HyperPlay]:        Could not find game with appId = 64ae4a16486493204184d9aa in API, maybe this game was delisted
(09:47:43) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64ae4a16486493204184d9aa due to Error: GameId not find in API}
(09:47:43) WARNING: [HyperPlay]:        Could not find game with appId = 64742e70e61cddebcbb7bd68 in API, maybe this game was delisted
(09:47:43) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64742e70e61cddebcbb7bd68 due to Error: GameId not find in API}
(09:47:43) INFO:    [Gog]:              Saved user data to config
(09:47:44) INFO:    [Backend]:          Auto Updater found version: 0.5.0 released on 2023-08-17T03:43:26.215Z with name 0.5.0
(09:47:44) INFO:    [Backend]:          Deleting abort controller for legendary-version
(09:47:44) INFO:    [Backend]:          Creating abort controller for gogdl-version
(09:47:44) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(09:47:44) INFO:    [Backend]:          Loading Screen Ready
(09:47:44) INFO:    [Frontend]:         Refreshing Library
(09:47:44) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(09:47:44) INFO:    [Legendary]:        Refreshing library...
(09:47:44) INFO:    [Legendary]:        Refreshing Epic Games...
(09:47:44) INFO:    [Gog]:              Getting GOG library
(09:47:44) INFO:    [Legendary]:        Game list updated, got 356 games & DLCs
(09:47:44) INFO:    [Backend]:          Frontend Ready
(09:47:45) INFO:    [Backend]:          Creating abort controller for legendary-refresh
(09:47:45) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(09:47:45) INFO:    [WineDownloader]:   Updating wine versions info
(09:47:45) INFO:    [WineDownloader]:   Fetching upstream information...
(09:47:45) INFO:    [Gog]:              Number of library pages: 1
(09:47:45) WARNING: [HyperPlay]:        Could not find game with appId = 64ae4a16486493204184d9aa in API, maybe this game was delisted
(09:47:45) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64ae4a16486493204184d9aa due to Error: GameId not find in API}
(09:47:45) WARNING: [HyperPlay]:        Could not find game with appId = 64742e70e61cddebcbb7bd68 in API, maybe this game was delisted
(09:47:45) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64742e70e61cddebcbb7bd68 due to Error: GameId not find in API}
(09:47:46) INFO:    [Gog]:              Saved games data
(09:47:46) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(09:47:47) INFO:    [WineDownloader]:   wine versions updated
(09:47:47) ERROR:   [Backend]:          Could not find default wine version
(09:47:47) INFO:    [Backend]:          Deleting abort controller for legendary-refresh
(09:47:49) INFO:    [Backend]:          Deleting abort controller for legendary-refresh
(09:47:49) INFO:    [Backend]:          Starting the Download Queue
(09:47:55) INFO:    [Backend]:          

HyperPlay Version: 0.5.0
Legendary Version:  0.20.32 Dark Energy (hotfix #6)
GOGdl Version: 0.6
OS: Microsoft Windows 10 Education KERNEL: 10.0.19045 ARCH: x64
CPU: Intel Core™ i7-6700K @4 
RAM: Total: 63.96 GiB Available: 45.64 GiB
GRAPHICS: GPU0: NVIDIA GeForce RTX 2060 VRAM: 12288MB DRIVER: 536.99 


(09:48:19) INFO:    [ExtraGameInfo]:    Using cached ExtraGameInfo data for The Fabled
(09:48:19) INFO:    [HyperPlay]:        Getting install info for The Fabled
(09:48:19) INFO:    [HyperPlay]:        Getting install info for The Fabled
(09:48:19) INFO:    [HyperPlay]:        Getting install info for The Fabled
(09:48:20) INFO:    [Backend]:          Launching The Fabled (0xf0589f4e59a35c16fd3bfc6dc3ab3e98bec447c8b2a91c96c84441d6dc78be97)
(09:48:20) INFO:    [Backend]:          Preventing display from sleep
(09:48:20) INFO:    [HyperPlay]:        Getting install info for The Fabled
(09:48:20) INFO:    [HyperPlay]:        Getting install info for The Fabled
(09:48:20) INFO:    [Backend]:          launching native sideloaded or hyperplay store game: C:\Users\Joe\Games\HyperPlay\thefabled\thefabled\thefabled\thefabled.exe 
(09:48:20) INFO:    [Backend]:          Creating abort controller for 0xf0589f4e59a35c16fd3bfc6dc3ab3e98bec447c8b2a91c96c84441d6dc78be97
(09:48:20) INFO:    [Backend]:          Backend: LD_PRELOAD= C:\Users\Joe\Games\HyperPlay\thefabled\thefabled\thefabled\C:\Users\Joe\Games\HyperPlay\thefabled\thefabled\thefabled\thefabled.exe
(09:48:20) DEBUG:   [Backend]:          Logging to file "C:\Users\Joe\AppData\Roaming\hyperplay\GamesConfig\0xf0589f4e59a35c16fd3bfc6dc3ab3e98bec447c8b2a91c96c84441d6dc78be97-lastPlay.log"
(09:48:20) INFO:    [Backend]:          overlay is shown ignoring mouse events:  {
  "overlayIsShown": false
}
(09:48:21) INFO:    [Frontend]:         Refreshing Library
(09:48:21) WARNING: [Backend]:          refresh not implemented on Sideload Library Manager
(09:48:21) INFO:    [Legendary]:        Refreshing library...
(09:48:21) INFO:    [Legendary]:        Refreshing Epic Games...
(09:48:21) INFO:    [Gog]:              Getting GOG library
(09:48:21) INFO:    [Legendary]:        Game list updated, got 356 games & DLCs
(09:48:21) INFO:    [Backend]:          Creating abort controller for legendary-refresh
(09:48:21) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary list --third-party
(09:48:22) WARNING: [HyperPlay]:        Could not find game with appId = 64ae4a16486493204184d9aa in API, maybe this game was delisted
(09:48:22) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64ae4a16486493204184d9aa due to Error: GameId not find in API}
(09:48:22) WARNING: [HyperPlay]:        Could not find game with appId = 64742e70e61cddebcbb7bd68 in API, maybe this game was delisted
(09:48:22) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64742e70e61cddebcbb7bd68 due to Error: GameId not find in API}
(09:48:22) INFO:    [Gog]:              Number of library pages: 1
(09:48:23) INFO:    [Gog]:              Saved games data
(09:48:25) INFO:    [Backend]:          Deleting abort controller for legendary-refresh
(09:48:33) INFO:    [Backend]:          Aborting 0xf0589f4e59a35c16fd3bfc6dc3ab3e98bec447c8b2a91c96c84441d6dc78be97
(09:48:33) INFO:    [Backend]:          Aborted 0xf0589f4e59a35c16fd3bfc6dc3ab3e98bec447c8b2a91c96c84441d6dc78be97
(09:48:33) INFO:    [Backend]:          Trying to kill C:\Users\Joe\Games\HyperPlay\thefabled\thefabled\thefabled\thefabled.exe
(09:48:33) INFO:    [Backend]:          Killed C:\Users\Joe\Games\HyperPlay\thefabled\thefabled\thefabled\thefabled.exe
(09:48:33) INFO:    [Backend]:          Trying to kill TheFabled.exe
(09:48:34) INFO:    [Backend]:          Killed TheFabled.exe
(09:48:34) INFO:    [Backend]:          Abort command "LD_PRELOAD= C:\Users\Joe\Games\HyperPlay\thefabled\thefabled\thefabled\C:\Users\Joe\Games\HyperPlay\thefabled\thefabled\thefabled\thefabled.exe"
(09:48:34) INFO:    [Backend]:          Stopping Display Power Saver Blocker
(09:48:34) INFO:    [Frontend]:         Refreshing Library
(09:48:34) INFO:    [HyperPlay]:        Getting install info for The Fabled
(09:48:34) INFO:    [HyperPlay]:        Getting install info for The Fabled
(09:48:34) WARNING: [HyperPlay]:        Could not find game with appId = 64ae4a16486493204184d9aa in API, maybe this game was delisted
(09:48:34) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64ae4a16486493204184d9aa due to Error: GameId not find in API}
(09:48:34) WARNING: [HyperPlay]:        Could not find game with appId = 64742e70e61cddebcbb7bd68 in API, maybe this game was delisted
(09:48:34) ERROR:   [HyperPlay]:        Could not refresh HyperPlay Game with appId = 64742e70e61cddebcbb7bd68 due to Error: GameId not find in API}
(09:48:35) INFO:    [HyperPlay]:        Getting install info for The Fabled
(09:48:35) INFO:    [HyperPlay]:        Getting install info for The Fabled
(09:48:38) INFO:    [Backend]:          Creating abort controller for legendary-version
(09:48:38) INFO:    [Legendary]:        Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary --version
(09:48:38) INFO:    [Backend]:          Creating abort controller for gogdl-version
(09:48:38) INFO:    [Gog]:              Running command: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\gogdl --version
(09:48:38) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(09:48:38) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(09:48:39) INFO:    [Backend]:          Deleting abort controller for gogdl-version
(09:48:39) INFO:    [Backend]:          Deleting abort controller for legendary-version
(09:48:40) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(09:48:40) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(09:48:40) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(09:48:40) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(09:48:40) INFO:    [Backend]:          Creating abort controller for 98bc04bc842e4906993fd6d6644ffb8d
(09:48:40) INFO:    [Legendary]:        Checking if EOS Overlay is enabled: C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info
(09:48:41) INFO:    [Backend]:          Aborting 98bc04bc842e4906993fd6d6644ffb8d
(09:48:41) INFO:    [Backend]:          Aborted 98bc04bc842e4906993fd6d6644ffb8d
(09:48:41) INFO:    [Legendary]:        Abort command "C:\Users\Joe\AppData\Local\Programs\hyperplay\resources\app.asar.unpacked\build\bin\win32\legendary eos-overlay info"
(09:48:41) INFO:    [Backend]:          Deleting abort controller for 98bc04bc842e4906993fd6d6644ffb8d
```

### Steps to reproduce

1. Launch The Fabled
2. Open the overlay and click the Exit button
3. Observe the overlay does close but the game remains open

### Expected behavior

The game closes along with the overlay when the Exit button is clicked

### hyperplay Version

Latest Stable

### System Information

- Windows 10
- hyperplay Version 0.5.0

**Comment by BrettCleary** [comment]
I believe this is resolved @nyghtstalker can you confirm?

**Comment by nyghtstalker** [comment]
@BrettCleary I confirmed this is still occurring with Bushi.

**Comment by BrettCleary** [comment]
bootstrapped games have two processes, the bootstrapper and the game. window.api.kill only kills the bootstrapper process. we need to also destroy all processes spawned by this process

**Comment by nyghtstalker** [comment]
List of games currently experiencing this issue:
1. Bushi
2. Synergy Land

**Comment by awantoch** [comment]
@nyghtstalker to enumerate games still having this issue

**Comment by nyghtstalker** [comment]
This is no longer occuring. Closing ticket.
